<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="$(CoverletVersion)" />
        <PackageReference Include="FluentAssertions" Version="$(FluentAssertionsVersion)" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="$(PlataformaVersion)" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="$(TestSdkVersion)" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="$(PlataformaVersion)" />
        <PackageReference Include="Testcontainers.PostgreSql" Version="$(TestcontainersVersion)" />
        <PackageReference Include="xunit" Version="$(XunitVersion)" />
        <PackageReference Include="xunit.runner.visualstudio" Version="$(XunitRunnerVersion)" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\MovimentacoesFinanceiras.Api\MovimentacoesFinanceiras.Api.csproj" />
    </ItemGroup>

</Project>
