<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <!-- Não incluído no CI; executado sob demanda -->
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NBomber" Version="$(NBomberVersion)" />
    <PackageReference Include="NBomber.Http" Version="$(NBomberVersion)" />
  </ItemGroup>

</Project>
