<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="$(CoverletVersion)" />
        <PackageReference Include="FluentAssertions" Version="$(FluentAssertionsVersion)" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="$(TestSdkVersion)" />
        <PackageReference Include="NSubstitute" Version="$(NSubstituteVersion)" />
        <PackageReference Include="xunit" Version="$(XunitVersion)" />
        <PackageReference Include="xunit.runner.visualstudio" Version="$(XunitRunnerVersion)" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\MovimentacoesFinanceiras.Worker\MovimentacoesFinanceiras.Worker.csproj" />
    </ItemGroup>

</Project>
